export const GET_ALL_GAMES = "GET_ALL_GAMES";
export const POST_GAME = "POST_GAME";
export const PAGINATE = "PAGINATE";
export const GET_DETAIL = "GET_DETAIL";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const GET_GENRES = "GET_GENRES";
export const GET_PLATFORMS = "GET_PLATFORMS";
export const GET_BY_NAME= "GET_BY_NAME";
export const NOT_FOUND= "NOT_FOUND";
export const CLEAN_FILTERED= "CLEAN_FILTERED";
export const ORDER= "ORDER";
export const DELETE_DBGAME= "DELETE_DBGAME";
export const FILTERED_BY_SOURCE= "FILTERED_BY_SOURCE";
export const FILTERED_BY_GENRES = "FILTERED_BY_GENRES"
export const FILTERED_BY_PLATFORMS= "FILTERED_BY_PLATFORMS"
export const IS_LOADING= "IS_LOADING"


